# Generated by Django 5.1.6 on 2025-02-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('size', models.CharField(max_length=10, verbose_name='Talla')),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True)),
            ],
        ),
    ]
